#!/bin/bash
echo "=== Debugging Packaged App ==="
echo ""
echo "To test the new packaged app:"
echo "1. DMG is open now"
echo "2. Install from DMG if not already installed"
echo "3. Launch the app"
echo "4. Open Console.app (Applications > Utilities)"
echo "5. Search for 'ClipForge' to see logs"
echo ""
echo "Look for these log messages:"
echo "- [FFmpeg] Using production paths: { resourcesPath, ffmpegPath, ffprobePath }"
echo "- FFmpeg configured - Binary: /path/to/ffmpeg"
echo ""
echo "If you see errors about paths, share the console output"
