#!/bin/bash
echo "=== ClipForge DMG Test Script ==="
echo ""
echo "DMG Location: $(pwd)/dist/ClipForge-1.0.0-arm64.dmg"
echo "Size: 683MB"
echo ""
echo "Steps to test:"
echo "1. DMG should be open now"
echo "2. Drag ClipForge to Applications folder in the DMG"
echo "3. Open Applications folder on your Mac"
echo "4. Find ClipForge.app and double-click"
echo "5. If you see 'damaged' warning: Right-click → Open → Open"
echo ""
echo "Testing checklist:"
echo "- [ ] App launches without errors"
echo "- [ ] Can import a video file"
echo "- [ ] Can play video with audio"
echo "- [ ] Can set trim points"
echo "- [ ] Can export video (CRITICAL TEST)"
echo ""
echo "Open Console.app to see logs if you encounter errors"
